[project]
name = "library-management-system"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bcrypt<4.0",
    "fastapi-pagination>=0.15.14",
    "fastapi[standard]>=0.136.0",
    "passlib[bcrypt]>=1.7.4",
    "psycopg2>=2.9.12",
    "pydantic-settings>=2.13.1",
    "python-jose[cryptography]>=3.5.0",
    "python-multipart>=0.0.26",
    "sqlalchemy>=2.0.50",
    "langchain-google-genai>=2.0",
    "langchain-core>=0.3",
    "langgraph>=1.2.8",
    "langgraph-checkpoint-sqlite>=2.0",
    "langgraph-checkpoint-postgres>=2.0",
    "alembic>=1.18.5",
    "pgvector>=0.5.0",
    "sentence-transformers>=5.5.1",
    "psycopg[binary]>=3.3.4",
    "psycopg-pool>=3.3.1",
]
