"""add book copies

Revision ID: 4f4e85aaa11b
Revises: c56787071253
Create Date: 2026-07-12 11:56:17.231019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f4e85aaa11b'
down_revision: Union[str, Sequence[str], None] = 'c56787071253'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_copies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('copy_number', sa.Integer(), nullable=False),
    sa.Column('condition', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('acquired_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_copies_id'), 'book_copies', ['id'], unique=False)
    op.add_column('borrow_records', sa.Column('copy_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'borrow_records', 'book_copies', ['copy_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'borrow_records', type_='foreignkey')
    op.drop_column('borrow_records', 'copy_id')
    op.drop_index(op.f('ix_book_copies_id'), table_name='book_copies')
    op.drop_table('book_copies')
    # ### end Alembic commands ###
